### ISSUE TITLE
Question: Maximum Cababilies of Polling Encoder Library

### ISSUE THREAD

**Issue by thatrobotguy** [luni64/PollEncoder#1]
Hey I was just wondering
I want to do some encoder counting with several encoders (4 total) on a Teensy 4.0. The maximum theoretical ticks per second is around 50 KHz. I am using quadrature encoders. Would this library still work or would interrupts still be required? I am also hoping to send this data over a serial bus like UART or CAN. Would this be possible? It is okay if it is not. I am still investigating different Teensy libraries. Maybe the question is not IF but at what lowest clock freq possible (since the 4.0 can go to 600 MHz)?

Thanks

**Comment by luni64** [comment]
50kHz 4 Encoders should be no problem. I  have a T3.2 with 4 encoders running in front of me (mulitplexed with a 74165, using the schematic shown in the Eagle folder).  If you connect them directly it will be a bit more effective (but not dramatically).

Here the results of the quick test. The trace shows a test pin which is high during the readout of the encoders which takes about 4.5µs. I read out with 50kHz so this gives a total load of about 21% on a T3.2. 

![image](https://user-images.githubusercontent.com/12611497/74609863-962a1400-50ee-11ea-9f84-03272943c15d.png)

Here the used code:
```c++
#include "Arduino.h"
#include "EncPlex.h"

constexpr unsigned encoderCount = 4; // number of attached  (daisy chain shift regesters for more than 8)

constexpr unsigned pinLD = 14;  //load pin for all shift registers)
constexpr unsigned pinCLK = 15; //clock pin for all shift registers
constexpr unsigned QH_A = 0;    //output pin QH of shift register A
constexpr unsigned QH_B = 1;    //output pin QH of shift register B
                                //74165 datasheet: http://www.ti.com/product/SN74HC165

EncPlex74165 encoders(encoderCount, pinLD, pinCLK, QH_A, QH_B);

void setup()
{
    (new IntervalTimer)->begin([]{encoders.tick();}, 20);
}
elapsedMillis stopwatch = 0;

void loop()
{
    if (stopwatch > 200)  // display encoder values every 200 ms
    {
        for (unsigned i = 0; i < encoderCount; i++)
        {
            Serial.printf("E%u:%3d ", i, encoders[i].read());
        }
        Serial.println();
        stopwatch = 0;
    }
}
```
### Teensy 4
I need to add some wait cycles in the library for T4, otherwise it will be too fast for the 74165. I can redo this with a T4 tomorrow.

**Comment by luni64** [comment]
BTW: I just published https://github.com/luni64/EncPlex a follow up lib to this one. (I didn't like the name). So, would be good to move the conversation to the new lib. I'll shut this one down in a couple of days.

**Comment by thatrobotguy** [comment]
Hey,
I appreciate your quick response.
A Teensy load of 21% does not sound bad by any standard, so I should be good to go. I will want to wire directly to the Teensy since I don't have that chip and I want the software to be a little more straightforward. It appears, however, that this library is meant for a different purpose than intended, so I will consider this an answered question.

**Comment by luni64** [comment]
Oh, the library can do directly connected encoders as well. 

Anyway, just thinking why don't you use the hardware quadrature decoders?https://github.com/mjs513/Teensy-4.x-Quad-Encoder-Library That should readout your encoders without any software load. I tried it a couple of weeks ago with 1MHz count rate and it worked without issues https://forum.pjrc.com/threads/58478-Teensy-4-x-H-W-Quadrature-Encoder-Library?p=222989&viewfull=1#post222989

**Comment by thatrobotguy** [comment]
I did not know about that library. I will look into it. Thanks man 👍
